services:
  mongo:
    image: mongo:latest
    container_name: loan-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: Loan-App
    volumes:
      - mongo-data:/data/db
      
volumes:
  mongo-data:
